title: Guiselle Armstrong
baseURL: https://guisellearmstrong.com/
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableRobotsTXT: true
enableGitInfo: false
disableGenerator: true

minify:
  minifyOutput: true
  tdewolfe/minify:
    keep-css-arguments: true

build:
  noChmod: true
  noJSDInHead: true

permalinks:
  blog: /blog/:slug/
  projects: /projects/:slug/
  publications: /publications/:slug/
  events: /events/:slug/
  courses: /courses/:slug/

taxonomies:
  author: authors
  tag: tags
  category: categories
  publication_type: publication_types

params:
  environment: production

outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - RSS
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  term:
    - HTML
    - RSS

paginate: 20
pagination:
  pagerSize: 20
  path: page

privacy:
  youtube:
    privacyEnhanced: true