main:
  - name: Home
    url: /
    weight: 1
  - name: Experience
    url: /experience/
    weight: 2
  - name: Volunteer
    url: /volunteer/
    weight: 3
  - name: Projects
    url: /projects/
    weight: 4
  - name: Contact
    url: /#contact
    weight: 5
